title: Odera Tech Site
email: enoscarter@gmail.com
author: Odera
copyright: "Unpublished Work (cleft) 2017-{currentYear} {author}"
description: >- # this means to ignore newlines until "baseurl:"
  Tech is the future. To survive the coming revolutions one has 
  to be well-equipped technologically. The people who took advantage of the Industrial
  Revolution did well for themselves. Will you do well for yourself in this tech revolution?
